from selenium import webdriver
from time import sleep
driver=webdriver.Chrome("./chromedriver")
driver.get("https://www.monsterindia.com/")
sleep(5)
#driver.close()
#driver.quit()
#handles=driver.window_handles
driver.find_element_by_xpath('//input[@name="fts"]').send_keys("Python")
sleep(3)
driver.find_element_by_xpath("(//strong[text()='Python'])[1]").click()
sleep(3)
driver.find_element_by_xpath("//input[@value='Search']").click()
sleep(2)
#driver.find_element_by_xpath("(//span[text()='Jobseeker Login'])[2]").click()
#sleep(2)
#driver.find_element_by_xpath('//input[@id="signInName"]').send_keys('chandana')
#sleep(3)
#driver.find_element_by_xpath('//input[@id="password"]').send_keys('chandana12')
#sleep(3)
#driver.find_element_by_xpath('//input[@value="Login"]').click()
#sleep(3)
driver.find_element_by_xpath("(//a[text()='Python Developer'])[1]").click()
sleep(2)
handles=driver.window_handles
driver.switch_to.window(handles[1])
driver.find_element_by_xpath("//div[text()='About the Job in Detail']/../..//button[text()='APPLY']").click()
sleep(2)
driver.switch_to.window(handles[0])
driver.find_element_by_xpath("(//span[text()='Jobseeker Login'])[2]").click()
